<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CoinStack</RootNamespace>
    <AssemblyName>CoinStack</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="7.0.0" />
    <PackageReference Include="LLamaSharp" Version="0.27.0" />
    <PackageReference Include="LLamaSharp.Backend.Vulkan" Version="0.27.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoinStack.Data\CoinStack.Data.csproj" />
  </ItemGroup>

</Project>